ServerName                      "UBI9 FTP Server"
ServerType                      standalone
DefaultServer                   on

Port                            21
PassivePorts                    30000 30009

User                            nobody
Group                           nobody

UseIPv6                         off
RequireValidShell               off

AuthOrder                       mod_auth_unix.c

<Directory /home/ftpuser>
  AllowOverwrite                on
  <Limit ALL>
    AllowAll
  </Limit>
</Directory>